/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Image */

#ifndef _Included_Image
#define _Included_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Image
 * Method:    readTiff
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Image_readTiff
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
